// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudDCsrH21e9nzWYQMMSLy47SYiC5d_3Y',
    appId: '1:635972849063:web:df624ee149836ec7d33a82',
    messagingSenderId: '635972849063',
    projectId: 'gear-13c34',
    authDomain: 'gear-13c34.firebaseapp.com',
    storageBucket: 'gear-13c34.appspot.com',
    measurementId: 'G-3JKVPCMK3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJBUyVfORuoegdptJ9iqg7Q7VFx-R2iIQ',
    appId: '1:635972849063:android:7b91f91ea8201028d33a82',
    messagingSenderId: '635972849063',
    projectId: 'gear-13c34',
    storageBucket: 'gear-13c34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuKIwsWZuk2MD_WEhDH7rc1Z-PjoBApPU',
    appId: '1:635972849063:ios:82dbe3ea0e4becbcd33a82',
    messagingSenderId: '635972849063',
    projectId: 'gear-13c34',
    storageBucket: 'gear-13c34.appspot.com',
    iosClientId: '635972849063-dqvbr6v5i2e1khub49rs08dfbjum6q74.apps.googleusercontent.com',
    iosBundleId: 'com.mea.gear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuKIwsWZuk2MD_WEhDH7rc1Z-PjoBApPU',
    appId: '1:635972849063:ios:82dbe3ea0e4becbcd33a82',
    messagingSenderId: '635972849063',
    projectId: 'gear-13c34',
    storageBucket: 'gear-13c34.appspot.com',
    iosClientId: '635972849063-dqvbr6v5i2e1khub49rs08dfbjum6q74.apps.googleusercontent.com',
    iosBundleId: 'com.mea.gear',
  );
}
